name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy
        env:
          HEROKU_APP_NAME:    ${{ secrets.HEROKU_APP_NAME }}
          HEROKU_API_TOKEN:   ${{ secrets.HEROKU_API_TOKEN }}
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        run: make deploy